name: srec
description: A Dart library that can read and write Motorola S-Record files. The Motorola S-Record is a file format that contains binary information as ASCII text.
version: 1.2.0
repository: https://github.com/domohuhn/srec
issue_tracker: https://github.com/domohuhn/srec/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  intel_hex: ^1.4.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.16.0

